<?php

if(!defined('SITUATION_PROFESSIONNELLE_SALARIER')) define('SITUATION_PROFESSIONNELLE_SALARIER', 'salarier');
if(!defined('SITUATION_PROFESSIONNELLE_NON_SALARIER')) define('SITUATION_PROFESSIONNELLE_NON_SALARIER', 'non_salarier');